spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:disabled}
            client-secret: ${GOOGLE_CLIENT_SECRET:disabled}
            scope:
              - email
              - profile
            redirect-uri: "https://0b51c4e4f6d6.ngrok-free.app/login/oauth2/code/{registrationId}"
            client-name: Google
          
#          apple:
#            client-id: ${APPLE_CLIENT_ID:disabled}
#            client-secret: ${APPLE_CLIENT_SECRET:disabled}
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_post
#            scope:
#              - name
#              - email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: Apple
          
          kakao:
            client-id: ${KAKAO_CLIENT_ID:disabled}
            client-secret: ${KAKAO_CLIENT_SECRET:disabled}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            redirect-uri: "https://0b51c4e4f6d6.ngrok-free.app/login/oauth2/code/{registrationId}"
            client-name: Kakao
        
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-name-attribute: sub
          
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id