spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aido_backend?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username:
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true