version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: aido-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: >
      mysqld --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci
             --default-time-zone=+09:00
volumes:
  dbdata: